# Generated by Django 4.2 on 2023-05-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_recipe_cover_image_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-created_at',)},
        ),
    ]
