# Generated by Django 4.2 on 2023-06-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_recipe_slug_alter_comment_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_az',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
