version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./pgdb:/var/lib/postgresql/data

  web:
    container_name: food_stories
    build: .
    ports:
      - 8002:8000
    depends_on:
      - "db"
      - "redis"
    env_file:
      - .env
      


  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080